version: '3.9'

services:
  db:
    image: postgres:13-alpine
    volumes:
      # - pg_data:/var/lib/postgresql/data/
      # - ./dump.sql:/docker-entrypoint-initdb.d/dummy_dump.sql
      - ./database.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    expose:
      - 5432
    environment:
      - PORT=5000
      - NODE_ENV=production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=sales
    networks:
      - web

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=test123
      - DB_NAME=sales
      - EXC_API_KEY=API_KEY_HERE
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/backend/uploads
    networks:
      - web

  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    depends_on:
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web

  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - BACKEND_PORT=5000  
    depends_on:
      - nginx
    ports:
      - "80:80"
    networks:
      - web


networks:
  web:
    external: true

volumes:
  pg_data: