version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  react:
    build: ./frontend
    depends_on:
      - backend
      - nginx
    ports:
      - "80:80"


