version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
    volumes:
      - ./backend/uploads:/backend/uploads

  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=5000  
    depends_on:
      - backend
      - nginx
    ports:
      - "80:80"


